# Generated by Django 2.2 on 2021-12-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_db_project_mock1_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_project',
            name='mock1_counts',
        ),
    ]
