# Generated by Django 2.2 on 2021-12-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_remove_db_project_mock1_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project',
            name='mocks',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
