# Generated by Django 2.2 on 2021-12-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_db_project_mocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_project',
            name='mock_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='db_project',
            name='mocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='db_project',
            name='run_counts',
            field=models.IntegerField(default=0),
        ),
    ]
