# Generated by Django 2.2 on 2021-12-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_auto_20211215_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_mock',
            name='mock_response_body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
