# Generated by Django 2.2 on 2021-12-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_auto_20211222_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_mock',
            name='mock_response_body_lj',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='db_mock',
            name='model',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='db_mock',
            name='response_header',
            field=models.CharField(blank=True, default='{}', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_mock',
            name='state_code',
            field=models.IntegerField(default=200),
        ),
    ]
