# Generated by Django 2.2 on 2021-12-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_auto_20211227_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_mock',
            name='model',
            field=models.TextField(blank=True, default='fx', max_length=30, null=True),
        ),
    ]
