# Generated by Django 2.2 on 2021-12-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_auto_20211227_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_mock',
            old_name='response_header',
            new_name='response_headers',
        ),
    ]
