# Generated by Django 2.2 on 2022-01-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0012_auto_20211227_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_mock',
            name='mock_time',
            field=models.FloatField(default=0),
        ),
    ]
