# Generated by Django 2.2 on 2022-01-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0013_db_mock_mock_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project',
            name='catch_log',
            field=models.TextField(default='[]'),
        ),
    ]
