# Generated by Django 2.2 on 2022-01-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0017_db_project_catch_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('method', models.CharField(max_length=200, null=True)),
                ('body', models.CharField(max_length=200, null=True)),
                ('result', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
