# Generated by Django 2.2 on 2022-02-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0019_db_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_api',
            name='testcases',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='db_case',
            name='check',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
